baseURL = "/"
languageCode = "fr-ca"
defaultContentLanguage = "fr"
title = "Blogue de Jordan Chénard"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "https://bsky.app/profile/jordanchenard.ca"

  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = true

  addFrame = true
  addDot = true

  highlightColor = '#7b16ff'

  dateFormat = "02 janvier 2006"
  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true